language: java
jdk: openjdk11
branches:
  only:
  - master
git:
  depth: false
install: true
script: "/bin/bash .travis/build.sh $encrypted_df8d49f7d896_key $encrypted_df8d49f7d896_iv"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: BCimaVByInd1Fo4weaHg0oeyoRzdG0RR7c8MVklJfsxM/LN/ZZYPJ5I+aBtHbahpGQ7BzzgNrOhamCZGzHhMWdobAqE0qSnK/kHtF0rqO9CgnCgML4Qs1mBw5sOI+cF5GqUSCGrgYZtcuM7bSAsxrvOlYVOKiddb2Tk9bElnsN8=
  - secure: jO9A8Z1/5pAFtMBDIo2hUqlkGAkcoobq/wKAFk9sPY6DYpz0CNnIRNjp+P76pGlOjg55aI/l/5H1sY0OqZQiC0JAw+hQjLJfKFU2FUvmSm9Hkm4Rt76zaudmxa0GfY8TfQpCOT0IUGM+12qB9aGQhx52pTYfqt4jw34M2/i9GD4=
  - secure: FvisncxATQSge+jmlBZIkpQhnObnmkjJQJLZeCG15LYgNUYnCEWtNhhNQx/BLR0g2vaRxWO/alCowO7NZWiys0OsMOQJeNbiewOcAj1LBugYCs/8FFXCwzkB63jf+U4MzoatACXIBdxLo7Vr9FRVuo18LBjGqx5tYqryEGtaym4=
  - secure: Q6GkwDYq1sAPG28g6fWx8pVhn6sykd7ZqCMppSiJAGvQxkb0rNd5I49DYEfntn2zxOoI3BHT8PtvDXme04V4bs4rfz/TJ+j79uxRwg8OKBeK7jEmIsI8tPRDzwKlOpV63wix/U6BabKSADzoXuoRIU5FADMfVLc0VTZT3Px811k=
